//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUONEP
    {
        public int ID { get; set; }
        public Nullable<int> HotRunner { get; set; }
        public Nullable<int> MaTrongLuong { get; set; }
        public Nullable<int> MaThoiGian { get; set; }
        public Nullable<int> MaCKNS { get; set; }
        public Nullable<long> MaMayKhuon { get; set; }
        public Nullable<int> MayLanhHD { get; set; }
        public Nullable<int> NhietDoML { get; set; }
        public Nullable<int> TayRobotHD { get; set; }
        public Nullable<int> TinHieuTRB { get; set; }
        public Nullable<int> SoNVLenKhuon { get; set; }
        public Nullable<int> SoNVDungMay { get; set; }
        public Nullable<int> MaNguyenLieu { get; set; }
        public string TenKCS { get; set; }
        public Nullable<int> DiemTB { get; set; }
        public string XepLoai { get; set; }
        public Nullable<int> MaPhePham { get; set; }
        public Nullable<int> CamBienTRB { get; set; }
        public Nullable<long> MaKhuon { get; set; }
    
        public virtual CHUKYNANGSUAT CHUKYNANGSUAT { get; set; }
        public virtual MayKhuon MayKhuon { get; set; }
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
        public virtual PHEPHAM PHEPHAM { get; set; }
        public virtual THOIGIANLENKHUON THOIGIANLENKHUON { get; set; }
        public virtual TRONGLUONG TRONGLUONG { get; set; }
        public virtual MayKhuon MayKhuon1 { get; set; }
    }
}
