//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MayKhuon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MayKhuon()
        {
            this.KHUONEPs = new HashSet<KHUONEP>();
            this.KHUONEPs1 = new HashSet<KHUONEP>();
            this.KHUONEPs2 = new HashSet<KHUONEP>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Equipment { get; set; }
        public string MaModel { get; set; }
        public string MaTaiSan { get; set; }
        public string TenMayKhuon { get; set; }
        public string TenNganCuaMay { get; set; }
        public string ViTri { get; set; }
        public string MaLoaiMay { get; set; }
        public string LoaiMay { get; set; }
        public Nullable<int> DangSuDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string WorkCenter { get; set; }
        public string KhuVuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUONEP> KHUONEPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUONEP> KHUONEPs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUONEP> KHUONEPs2 { get; set; }
    }
}
