//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectDBEntities : DbContext
    {
        public ProjectDBEntities()
            : base("name=ProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUKYNANGSUAT> CHUKYNANGSUATs { get; set; }
        public virtual DbSet<KHUONEP> KHUONEPs { get; set; }
        public virtual DbSet<MayKhuon> MayKhuons { get; set; }
        public virtual DbSet<NGUYENLIEU> NGUYENLIEUx { get; set; }
        public virtual DbSet<PHEPHAM> PHEPHAMs { get; set; }
        public virtual DbSet<THOIGIANLENKHUON> THOIGIANLENKHUONs { get; set; }
        public virtual DbSet<TRONGLUONG> TRONGLUONGs { get; set; }
    }
}
