//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHEPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHEPHAM()
        {
            this.KHUONEPs = new HashSet<KHUONEP>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DinhMuc { get; set; }
        public Nullable<int> SLPheXa { get; set; }
        public Nullable<int> SoShotPX { get; set; }
        public Nullable<int> SoShotPRH { get; set; }
        public Nullable<int> Tong { get; set; }
        public Nullable<int> ChenhLech { get; set; }
        public string LyDoLech { get; set; }
        public string BienPhap { get; set; }
        public Nullable<int> ChamDiem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUONEP> KHUONEPs { get; set; }
    }
}
