//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THOIGIANLENKHUON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THOIGIANLENKHUON()
        {
            this.KHUONEPs = new HashSet<KHUONEP>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> Chuan { get; set; }
        public Nullable<decimal> ThucTe { get; set; }
        public Nullable<decimal> ChenhLech { get; set; }
        public string LyDoLech { get; set; }
        public string BienPhap { get; set; }
        public Nullable<int> ChamDiem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUONEP> KHUONEPs { get; set; }
    }
}
